[2024-08-29 17:34:21,568] p12129 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/after_work.py:241} INFO - final df
[2024-08-29 17:34:21,582] p12129 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/after_work.py:243} INFO - final_df.shape (663, 25)
[2024-08-29 17:34:21,834] p12129 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/after_work.py:255} INFO - 445 unique cities saved
[2024-08-29 17:34:21,835] p12129 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/after_work.py:271} INFO - not handled 196 cities: {'Дальнереченск', 'пос. Персиановский', 'Кулебаки', 'Сосногорск', 'Малиновский', 'Берёзово', 'Воркута', 'Мариинск', 'Заполярный', 'Старая Русса', 'Артёмовский', 'Горноправдинск', 'Светлоград', 'п. Мурино', 'Лучегорск', 'Бирск', 'Удачный', 'Железнодорожный', 'Тамань', 'пгт. Новая Чара', 'Заинск', 'Снежинск', 'Холмск', 'Колпашево', 'Зубова Поляна', 'Анадырь', 'Урус-Мартан', 'Котельнич', 'Алексеевка', 'Краснознаменск', 'п. Придорожный', 'Топки', 'Буинск', 'Гусиноозёрск', 'Камышлов', 'Тарко-Сале', 'Донецк', 'п. Голышманово', 'Шимановск', 'Башкортостан Октябрьский', 'Красноармейск', 'Североуральск', 'Вихоревка', 'Лотошино', 'Козьмодемьянск', 'Сальск', 'Буй', 'ЗАТО Сибирский', 'Игрим', 'д. Жуковка', 'Избербаш', 'Малгобек', 'Зарайск', 'Фурманов', 'Сергиев Посад', 'Карабулак', 'р.п. Сенной', 'Свободный', 'Ува', 'пос. Саянский', 'Егорьевск', 'Пущино', 'п. Таксимо', 'Славгород', 'Кизляр', 'Шилка', 'Дзержинский', 'Федоровский', 'Борзя', 'Боготол', 'ст. Талица', 'п. Айхал', 'Дербент', 'Кемь', 'пгт. Забайкальск', 'Шали', 'Белоярский', 'Назрань', 'Могоча', 'Минеральные воды', 'Полярный', 'Кировск', 'Ноябрьск', 'Оса', 'Сортавала', 'Коряжма', 'Кушва', 'Звенигово', 'Кяхта', 'Иланский', 'пгт. Карымское', 'Суворов', 'Шарья', 'Балабаново', 'Болотное', 'Куровское', 'п. Ерофей Павлович', 'Баксан', 'Карталы', 'Хилок', 'Тербуны', 'Трёхгорный', 'Прохладный', 'Аргун', 'Амурск', 'Балтийск', 'п. Излучинск', 'Каспийск', 'Советская Гавань', 'Полярные зори', 'с. Красноселькуп', 'Завитинск', 'Гуково', 'Бронницы', 'Александров', 'Кукмор', 'Льгов', 'Железногорск-Илимский', 'Норильск', 'Вилючинск', 'Сегежа', 'Фролово', 'Семёнов', 'Хотьково', 'Дедовск', 'Тулун', 'Новый Оскол', 'Саров', 'Луховицы', 'Кимовск', 'Барабинск', 'Черноголовка', 'Ленск', 'п. Тазовский', 'Лесной', 'Хасавюрт', 'Черкесск', 'Новый Уренгой', 'Советский', 'п. Новый Ургал', 'пгт. Чернышевск', 'Покачи', 'Бологое', 'Гагарин', 'Фокино', 'Петровск-Забайкальский', 'ст. Павловская', 'Тайга', 'Ряжск', 'Строитель', 'Элиста', 'Губаха', 'Северобайкальск', 'Алдан', 'Агрыз', 'Урюпинск', 'Городец', 'Кингисепп', 'Муравленко', 'Гусев', 'Райчихинск', 'Нижнесортымский', 'Зима', 'Шахунья', 'Апшеронск', 'Жирновск', 'Миллерово', 'Арск', 'Таштагол', 'Йошкар-Ола', 'Грозный', 'Сковородино', 'Агинское', 'Шаховская', 'Кызыл', 'Заозёрск', 'Гудермес', 'Нальчик', 'Первомайск', 'п. Междуреченский', 'Озерск', 'п. Новоорск', 'Талдом', 'п. Светлый', 'Московский', 'Ейск', 'Мыски', 'п. Свободный', 'п. Ванино', 'Ершов', 'Моздок', 'Жуков', 'Алейск', 'Исилькуль', 'п. Магдагачи', 'Шумерля'}
[2024-08-29 17:34:27,478] p12158 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/after_work.py:241} INFO - final df
[2024-08-29 17:34:27,492] p12158 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/after_work.py:243} INFO - final_df.shape (616, 25)
[2024-08-29 17:34:27,711] p12158 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/after_work.py:255} INFO - 613 unique cities saved
[2024-08-29 17:34:27,712] p12158 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/after_work.py:271} INFO - not handled 22 cities: {'Мелеуз', 'Бугульма', 'Санкт-Петербург', 'Новороссийск', 'Вышний Волочёк', 'Краснокаменск', 'ст. Талица', 'Башкортостан Октябрьский', 'Черноголовка', 'Ишимбай', 'Волжск', 'Малиновский', 'Боровичи', 'Железнодорожный', 'Абакан', 'Ангарск', 'Федоровский', 'Иркутск', 'Гурьевск', 'д. Жуковка', 'Череповец', 'Норильск'}
[2024-09-02 10:52:14,643] p4511 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links.py:121} INFO - I will get links for 1 cities
[2024-09-02 10:52:14,643] p4511 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links.py:126} INFO - sleeping for 25.07 seconds
[2024-09-02 10:52:39,717] p4511 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links.py:129} INFO - get links for bank: sberbank, city: Воркута, yndx id: 224592002320
[2024-09-02 10:52:42,459] p4511 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-09-02 10:52:47,615] p4511 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links.py:55} INFO - sleep for 13.96
[2024-09-02 10:53:01,623] p4511 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links.py:74} INFO - sleep for 14.67
[2024-09-02 10:53:16,315] p4511 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links.py:32} INFO - loaded 13 ids
[2024-09-02 10:53:16,320] p4511 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links.py:74} INFO - sleep for 19.74
[2024-09-02 10:53:36,085] p4511 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links.py:32} INFO - loaded 13 ids
[2024-09-02 10:53:36,334] p4511 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links.py:152} INFO - 13 links saved for Воркута city
[2024-09-02 10:54:09,349] p4511 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links.py:166} INFO - left 0 cities
[2024-09-02 16:03:49,620] p8672 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/log.py:29} ERROR - Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py", line 169, in <module>
    get_links_for_cities(cities, path)
  File "/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py", line 129, in get_links_for_cities
    directory_name = f'{path}/links/{bank_name}'
NameError: name 'bank_name' is not defined
[2024-09-02 16:04:05,346] p8700 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:134} INFO - I will get links for 1 cities
[2024-09-02 16:04:05,346] p8700 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:139} INFO - sleeping for 29.65 seconds
[2024-09-02 16:04:35,001] p8700 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:142} INFO - get links for city: Воронеж
[2024-09-02 16:04:35,001] p8700 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:147} INFO - Error in get links for city: Воронеж, error: name 'yndx_id' is not defined
[2024-09-02 16:07:01,566] p8794 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:134} INFO - I will get links for 1 cities
[2024-09-02 16:07:01,566] p8794 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:144} INFO - sleeping for 38.69 seconds
[2024-09-02 16:07:40,260] p8794 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:147} INFO - get links for city: Воронеж
[2024-09-02 16:07:42,714] p8794 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-09-02 16:07:47,913] p8794 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:58} INFO - sleep for 14.34
[2024-09-02 16:08:02,268] p8794 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:106} INFO - driver stopped
[2024-09-02 16:08:02,554] p8794 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/urllib3/connectionpool.py:780} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104402430>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/81f888b222eec2eb3fac8e09b33a3991/window
[2024-09-02 16:08:02,554] p8794 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/urllib3/connectionpool.py:780} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044026d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/81f888b222eec2eb3fac8e09b33a3991/window
[2024-09-02 16:08:02,555] p8794 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/urllib3/connectionpool.py:780} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104402790>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/81f888b222eec2eb3fac8e09b33a3991/window
[2024-09-02 16:08:02,556] p8794 {/Users/anyarulina/parser/scripts/yandex_info_reviews_parser/get_links_new_logic.py:152} INFO - Error in get links for city: Воронеж, error: HTTPConnectionPool(host='localhost', port=52157): Max retries exceeded with url: /session/81f888b222eec2eb3fac8e09b33a3991/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104402910>: Failed to establish a new connection: [Errno 61] Connection refused'))
