[2024-04-26 10:56:24,692] p4374 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-04-26 10:56:38,509] p4374 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:47} INFO - business_aspect
[2024-04-26 10:56:38,510] p4374 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:48} INFO - 
[2024-04-26 10:56:38,522] p4374 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:191} INFO - error in get info for Рыбинск: name 'business_aspect' is not defined
[2024-04-26 10:57:19,929] p4472 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:159} INFO - all links length for Рыбинск city 1
[2024-04-26 10:57:20,815] p4472 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-04-26 10:57:35,081] p4472 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:47} INFO - business_aspect
[2024-04-26 10:57:35,082] p4472 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:48} INFO - 
[2024-04-26 10:57:35,095] p4472 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:191} INFO - error in get info for Рыбинск: name 'business_aspect' is not defined
[2024-04-26 12:20:10,904] p6557 {/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py:194} INFO - current limit is 500
[2024-04-26 12:20:13,120] p6557 {/Users/anyarulina/yandex-info-reviews-parser/log.py:32} ERROR - Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py", line 310, in <module>
    update_cities_dict(cities_list, bank_name)
  File "/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py", line 225, in update_cities_dict
    cities.update(cities_dict)
NameError: name 'cities' is not defined
[2024-04-26 12:20:27,698] p6586 {/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py:194} INFO - current limit is 499
[2024-04-26 12:20:29,893] p6586 {/Users/anyarulina/yandex-info-reviews-parser/log.py:32} ERROR - Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py", line 310, in <module>
    update_cities_dict(cities_list, bank_name)
  File "/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py", line 225, in update_cities_dict
    cities.update(cities_dict)
NameError: name 'cities' is not defined
[2024-04-26 12:21:53,130] p6641 {/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py:194} INFO - current limit is 498
[2024-04-26 12:21:55,357] p6641 {/Users/anyarulina/yandex-info-reviews-parser/log.py:32} ERROR - Logging an uncaught exception
Traceback (most recent call last):
  File "/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py", line 313, in <module>
    update_cities_dict(cities_list, bank_name)
  File "/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py", line 225, in update_cities_dict
    cities.update(cities_dict)
NameError: name 'cities' is not defined
[2024-04-26 12:22:15,101] p6670 {/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py:194} INFO - current limit is 497
[2024-04-26 12:22:17,350] p6670 {/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py:226} INFO - 1 cities updated in cities dictionary
[2024-04-26 12:23:25,021] p6706 {/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py:194} INFO - current limit is 496
[2024-04-26 12:23:25,213] p6706 {/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py:206} INFO - Ярцево yndx_id 1217811066
[2024-04-26 12:23:27,220] p6706 {/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py:226} INFO - 1 cities updated in cities dictionary
[2024-04-26 12:32:21,152] p7312 {/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py:192} INFO - current limit is 495
[2024-04-26 12:32:21,340] p7312 {/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py:204} INFO - Ярцево yndx_id 1217811066
[2024-04-26 12:32:23,346] p7312 {/Users/anyarulina/yandex-info-reviews-parser/call_yandex_api_org.py:225} INFO - 1 cities updated in cities dictionary
[2024-04-26 13:45:51,009] p9349 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:158} INFO - get info for banks in Рыбинск length of 1
[2024-04-26 13:45:51,821] p9349 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-04-26 13:46:11,140] p9349 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:47} INFO - business_aspect
[2024-04-26 13:46:11,142] p9349 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:48} INFO - 
[2024-04-26 13:46:11,158] p9349 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:190} INFO - Error in get info for banks in Рыбинск, error: name 'business_aspect' is not defined
[2024-04-26 13:47:43,190] p9485 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:158} INFO - get info for banks in Рыбинск length of 1
[2024-04-26 13:47:43,939] p9485 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-04-26 13:48:01,389] p9485 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:47} INFO - business_aspect
[2024-04-26 13:48:01,390] p9485 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:48} INFO - 
[2024-04-26 13:48:01,403] p9485 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:190} INFO - Error in get info for banks in Рыбинск, error: name 'business_aspect' is not defined
[2024-04-26 13:50:24,774] p9632 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:158} INFO - get info for banks in Рыбинск length of 1
[2024-04-26 13:50:25,547] p9632 {/Users/anyarulina/miniconda3/envs/main/lib/python3.9/site-packages/undetected_chromedriver/patcher.py:346} INFO - patching driver executable /Users/anyarulina/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2024-04-26 13:50:40,690] p9632 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:47} INFO - business_aspect
[2024-04-26 13:50:40,691] p9632 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:48} INFO - []
[2024-04-26 13:50:40,698] p9632 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:65} INFO - CAPTCHA CAPTCHA CAPTCHA CAPTCHA CAPTCHA CAPTCHA CAPTCHA CAPTCHA 
[2024-04-26 13:50:40,698] p9632 {/Users/anyarulina/yandex-info-reviews-parser/get_info.py:190} INFO - Error in get info for banks in Рыбинск, error: 'NoneType' object has no attribute 'start'
